/* WasmBridge 0.8 regression tests for removed ceilings and lifecycle fixes. */
"use strict";
const assert=require("assert"),fs=require("fs"),path=require("path"),vm=require("vm");
const root=path.resolve(__dirname,"..");
const binary=fs.readFileSync(path.join(root,"Examples/BufferArena/buffers.wasm"));
function context(){const c={WebAssembly,Promise,ArrayBuffer,Uint8Array,Uint8ClampedArray,Int8Array,Uint16Array,Int16Array,Uint32Array,Int32Array,Float32Array,Float64Array,Math,Object,Number,String,JSON,RangeError,Error,TypeError,fetch:()=>Promise.resolve({ok:true,arrayBuffer:()=>Promise.resolve(binary.buffer.slice(binary.byteOffset,binary.byteOffset+binary.byteLength))})};c.window=c;vm.createContext(c);["Runtime/wasmbridge.js","Runtime/module.js","Runtime/buffers.js","Runtime/package.js","Examples/BufferArena/buffers-fallback.js"].forEach(f=>vm.runInContext(fs.readFileSync(path.join(root,f),"utf8"),c,{filename:f}));return c;}
(async()=>{
 const c=context(), fallback=c.WasmBridgeBuffersFallback, opts={wasm:"buffers.wasm",fallback};
 const b=await c.WasmBridgeBuffers.load(opts);assert.strictEqual(b.backend,"wasm");assert.strictEqual(b.statistics().addressBits,32);assert.strictEqual(b.statistics().maxBufferBytes,null);
 const handles=[];for(let i=0;i<300;i++)handles.push(b.allocate(8));assert.strictEqual(b.statistics().activeBlocks,300);handles.forEach(h=>b.release(h));assert.strictEqual(b.statistics().activeBlocks,0);
 const big=b.allocate(40*1024*1024);b.write(big,new Uint8Array([9,8,7,6]));assert.deepStrictEqual(Array.from(b.read(big,4)),[9,8,7,6]);assert.ok(b.statistics().bytesInLinearMemory>32*1024*1024);b.release(big);
 const w=2048,h=2048,input=new Uint8ClampedArray(w*h*4);input[0]=1;input[1]=2;input[2]=3;input[3]=4;input[input.length-1]=77;const out=b.processRGBA(input,w,h);assert.strictEqual(out[0],254);assert.strictEqual(out[1],253);assert.strictEqual(out[2],252);assert.strictEqual(out[3],4);assert.strictEqual(out[out.length-1],77);assert.strictEqual(b.statistics().activeBlocks,0);
 const module=await c.WasmBridgeModule.load({wasm:"buffers.wasm",fallback,exports:["wb_active_count"],allocator:{allocate:"wb_alloc",release:"wb_free",capacity:"wb_capacity"}});assert.strictEqual(module.statistics().maxHandles,null);assert.strictEqual(module.statistics().maxBufferBytes,null);assert.strictEqual(module.statistics().maxMemoryBytes,null);const mh=module.allocate(8);module.release(mh);assert.throws(()=>module.read(mh),/released|Unknown/);
 let fail=true;const fake={memory:{buffer:new ArrayBuffer(65536),grow:()=>0},wb_alloc:()=>128,wb_free:()=>fail?0:1,wb_capacity:()=>16,ping:()=>1};const m2=await c.WasmBridgeModule.load({preferWasm:false,fallback:fake,exports:["ping"],allocator:{allocate:"wb_alloc",release:"wb_free",capacity:"wb_capacity"}});const fh=m2.allocate(8);assert.throws(()=>m2.dispose(),/release/);assert.strictEqual(m2.statistics().disposed,false);assert.strictEqual(m2.statistics().activeHandles,1);fail=false;assert.strictEqual(m2.dispose(),1);assert.strictEqual(m2.statistics().disposed,true);assert.throws(()=>m2.release(fh),/disposed/);
 const original=c.WebAssembly.instantiate;c.WebAssembly.instantiate=function(){throw new Error("sync explode");};const rec=await c.WasmBridge.load({wasm:"x",fallback:{answer:()=>42},exports:["answer"]});assert.strictEqual(rec.failurePhase,"instantiate");c.WebAssembly.instantiate=original;
 const loaded=[];const manifest={format:"wasmbridge-package-0.2",wasm:"module.wasm",fallback:"fallback.js",runtime:"wasmbridge.js",moduleRuntime:"module.js",adapter:"adapter.js",exports:["wb_active_count"],allocator:{allocate:"wb_alloc",release:"wb_free",capacity:"wb_capacity"},memoryExport:"memory"};const c2=context();await c2.WasmBridgePackage.load({manifest:"http://x/pkg/manifest.json",jsonLoader:()=>Promise.resolve(manifest),scriptLoader:u=>{loaded.push(u);return Promise.resolve();},fallback:c2.WasmBridgeBuffersFallback,preferWasm:false});assert.ok(loaded.some(x=>/adapter\.js$/.test(x)),"adapter script was not loaded");
 console.log("PASS: WasmBridge 0.8 hardening - no 16/32 MiB or 128-handle defaults, 2048 RGBA, retryable disposal, instantiate phase and package adapter loading.");
})().catch(e=>{console.error(e);process.exitCode=1;});
