/* WasmBridge RGBA8 scratch-buffer adapter; classic script, Firefox 52 compatible.
 * This is deliberately a bounded demo ABI (512x512), not the general allocator. */
(function (root) {
    "use strict";
    var NAMES=["wb_rgba_buffer","wb_rgba_capacity","wb_rgba_invert"];
    var MAX_SIDE=512,MAX_BYTES=MAX_SIDE*MAX_SIDE*4;
    function matches(value,Constructor){return value&&Object.prototype.toString.call(value)===Object.prototype.toString.call(new Constructor(0));}
    function checkMemory(exportsObject){if(!exportsObject.memory||!exportsObject.memory.buffer||!(exportsObject.memory.buffer instanceof ArrayBuffer))throw new Error("RGBA module must export linear memory.");}
    function validDimensions(width,height,input){if(typeof width!=="number"||typeof height!=="number"||width!==Math.floor(width)||height!==Math.floor(height)||width<1||height<1||width>MAX_SIDE||height>MAX_SIDE)throw new RangeError("RGBA dimensions must be integers from 1 to 512.");if(!matches(input,Uint8Array)&&!matches(input,Uint8ClampedArray))throw new TypeError("RGBA input must be Uint8Array or Uint8ClampedArray.");if(input.length!==width*height*4)throw new RangeError("RGBA input length must equal width * height * 4.");}
    function load(options){options=options||{};if(!root.WasmBridge||typeof root.WasmBridge.load!=="function")return Promise.reject(new Error("Load wasmbridge.js before rgba.js."));return root.WasmBridge.load({wasm:options.wasm,fallback:options.fallback,fallbackGlobal:options.fallbackGlobal||"WasmBridgeRGBAFallback",preferWasm:options.preferWasm,imports:options.imports||{},exports:NAMES,validateWasm:function(exportsObject){checkMemory(exportsObject);var capacity=exportsObject.wb_rgba_capacity(),offset=exportsObject.wb_rgba_buffer(),size=exportsObject.memory.buffer.byteLength;if(capacity<MAX_BYTES||capacity>size||offset<0||offset!==Math.floor(offset)||offset+capacity>size)throw new Error("RGBA module exposes invalid linear-memory bounds.");}}).then(function(processor){var exportsObject=processor.exports;checkMemory(exportsObject);return{backend:processor.backend,diagnostic:processor.diagnostic,capacity:exportsObject.wb_rgba_capacity(),processRGBA:function(pixels,width,height){validDimensions(width,height,pixels);var bytes=pixels.length,capacity=exportsObject.wb_rgba_capacity(),offset=exportsObject.wb_rgba_buffer(),memory=exportsObject.memory,buffer=memory.buffer;if(capacity<bytes||capacity>buffer.byteLength||offset<0||offset!==Math.floor(offset)||offset+capacity>buffer.byteLength)throw new RangeError("RGBA module returned invalid buffer bounds.");var view=new Uint8Array(buffer,offset,bytes);view.set(pixels);if(exportsObject.wb_rgba_invert(width,height)!==bytes)throw new Error("RGBA module rejected the image or returned wrong byte count.");if(buffer!==memory.buffer){buffer=memory.buffer;if(offset+bytes>buffer.byteLength)throw new RangeError("RGBA output lies outside grown memory.");view=new Uint8Array(buffer,offset,bytes);}var result=new Uint8ClampedArray(bytes);result.set(view);return result;}};});}
    root.WasmBridgeRGBA={load:load,version:"0.8.0",maxSide:MAX_SIDE};
}(this));
