param(
    [string]$LlvmRoot = $(if ($env:WASMBRIDGE_LLVM) { $env:WASMBRIDGE_LLVM } else { 'C:\clang+llvm-18.1.8-x86_64-pc-windows-msvc' }),
    [string]$ToolRoot = $(if ($env:WASMBRIDGE_TOOLS) { $env:WASMBRIDGE_TOOLS } else { 'C:\CODEX\TOOLS\WasmBridge' }),
    [switch]$RequireWasmToolchain,
    [switch]$Json
)
$ErrorActionPreference='Stop'
function Find-Vs2022 { $v=Join-Path ([Environment]::GetFolderPath('ProgramFilesX86')) 'Microsoft Visual Studio\Installer\vswhere.exe'; if(-not(Test-Path -LiteralPath $v)){return $null}; & $v -latest -products '*' -version '[17.0,18.0)' -property installationPath 2>$null }
function Get-PeArchitecture([string]$Path){$s=[IO.File]::OpenRead($Path);try{$r=New-Object IO.BinaryReader($s);$s.Position=0x3c;$o=$r.ReadInt32();$s.Position=$o+4;switch($r.ReadUInt16()){0x014c{'x86'}0x8664{'x64'}default{'unknown'}}}finally{$s.Dispose()}}
$vsRoot=Find-Vs2022;$msbuild=if($vsRoot){Join-Path $vsRoot 'MSBuild\Current\Bin\MSBuild.exe'}else{$null}
$v141=$null;if($vsRoot){$msvcRoot=Join-Path $vsRoot 'VC\Tools\MSVC';if(Test-Path -LiteralPath $msvcRoot){$v141=Get-ChildItem -LiteralPath $msvcRoot -Directory -ErrorAction SilentlyContinue|Where-Object{$_.Name -like '14.16*'}|Sort-Object Name -Descending|Select-Object -First 1}}
$v141cl=if($v141){Join-Path $v141.FullName 'bin\Hostx64\x64\cl.exe'}else{$null}
$win71='C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\Include\Windows.h'
$net40=Join-Path ([Environment]::GetFolderPath('ProgramFilesX86')) 'Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\mscorlib.dll'
$clang=Join-Path $LlvmRoot 'bin\clang.exe';$wasmLd=Join-Path $LlvmRoot 'bin\wasm-ld.exe';$targets='';if(Test-Path -LiteralPath $clang){$targets=(& $clang --print-targets 2>$null)-join "`n"};$wasm32=[bool]($targets -match '(?m)^\s*wasm32\s');$wasm64=[bool]($targets -match '(?m)^\s*wasm64\s')
$ff=@((Join-Path ([Environment]::GetFolderPath('ProgramFilesX86')) 'Mozilla Firefox\firefox.exe'),$(if($env:ProgramW6432){Join-Path $env:ProgramW6432 'Mozilla Firefox\firefox.exe'}else{Join-Path $env:ProgramFiles 'Mozilla Firefox\firefox.exe'}))|Where-Object{Test-Path -LiteralPath $_}|Select-Object -First 1
$node=Get-Command node.exe -ErrorAction SilentlyContinue|Select-Object -First 1
$portable=@{'wasm-validate.exe'=(Join-Path $ToolRoot 'wabt-1.0.42\bin\wasm-validate.exe');'wasm2js.exe'=(Join-Path $ToolRoot 'binaryen-version_133\bin\wasm2js.exe');'wasm-opt.exe'=(Join-Path $ToolRoot 'binaryen-version_133\bin\wasm-opt.exe');'esbuild.exe'=(Join-Path $ToolRoot 'esbuild-0.28.2\esbuild.exe')};$optional=[ordered]@{};foreach($n in $portable.Keys){$c=Get-Command $n -ErrorAction SilentlyContinue|Select-Object -First 1;$optional[$n]=if($c){$c.Source}elseif(Test-Path -LiteralPath $portable[$n]){$portable[$n]}else{$null}}
$report=[ordered]@{VisualStudio2022=[ordered]@{Found=[bool]$vsRoot;Root=$vsRoot;MSBuild=$(if($msbuild -and (Test-Path -LiteralPath $msbuild)){$msbuild}else{$null})};V141Xp=[ordered]@{Found=[bool]($v141cl -and (Test-Path -LiteralPath $v141cl));Version=$(if($v141){$v141.Name}else{$null});Compiler=$v141cl;Windows71A=(Test-Path -LiteralPath $win71)};NetFramework40=[ordered]@{Found=(Test-Path -LiteralPath $net40);ReferenceAssembly=$net40};LLVM=[ordered]@{Found=((Test-Path -LiteralPath $clang) -and (Test-Path -LiteralPath $wasmLd) -and $wasm32);Root=$LlvmRoot;Clang=$clang;WasmLd=$wasmLd;Wasm32=$wasm32;Wasm64=$wasm64};Firefox=[ordered]@{Found=[bool]$ff;Path=$ff;Version=$(if($ff){(Get-Item -LiteralPath $ff).VersionInfo.ProductVersion}else{$null});Architecture=$(if($ff){Get-PeArchitecture $ff}else{$null})};Node=[ordered]@{Found=[bool]$node;Path=$(if($node){$node.Source}else{$null})};OptionalTools=$optional}
$nativeReady=$report.VisualStudio2022.MSBuild -and $report.V141Xp.Found -and $report.V141Xp.Windows71A -and $report.NetFramework40.Found;$requiredReady=$nativeReady -and ((-not $RequireWasmToolchain) -or $report.LLVM.Found)
$report['NativeReady']=[bool]$nativeReady;$report['RequiredReady']=[bool]$requiredReady
if($Json){$report|ConvertTo-Json -Depth 5}else{Write-Host 'WasmBridge build-host environment';Write-Host ('  VS2022/MSBuild: '+$(if($report.VisualStudio2022.MSBuild){'OK'}else{'MISSING'}));Write-Host ('  v141_xp: '+$(if($report.V141Xp.Found){'OK - '+$report.V141Xp.Version}else{'MISSING'}));Write-Host ('  SDK 7.1A: '+$(if($report.V141Xp.Windows71A){'OK'}else{'MISSING'}));Write-Host ('  .NET Framework 4.0: '+$(if($report.NetFramework40.Found){'OK'}else{'MISSING'}));Write-Host ('  LLVM wasm32: '+$(if($report.LLVM.Found){'OK'}else{'not required/missing'}));Write-Host ('  LLVM wasm64: '+$(if($report.LLVM.Wasm64){'available'}else{'not available'}));Write-Host ('  Firefox: '+$(if($report.Firefox.Found){$report.Firefox.Version+' '+$report.Firefox.Architecture}else{'not found'}));Write-Host ('  Node host tests: '+$(if($report.Node.Found){'available'}else{'not found'}))}
if(-not$requiredReady){exit 1}
